### ISSUE TITLE
Failed - requirements installation

### ISSUE THREAD

**Issue by Rut-B** [saidwivedi/POCO#3]
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.4/5.4 MB 30.0 MB/s eta 0:00:00
hi @saidwivedi 
thanks of your repo. I trying to run your code and
during running requirements installation get error of:

  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Preparing metadata (pyproject.toml) ... error
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
---------------------------------------------------------------------------
CalledProcessError                        Traceback (most recent call last)
[<ipython-input-9-cf4d2835bbd9>](https://localhost:8080/#) in <cell line: 1>()

**Comment by saidwivedi** [comment]
Can you share the entire log?

**Comment by Rut-B** [comment]
This is my colab notebook 
https://colab.research.google.com/drive/11Mk1VItszbAIXQGOoVreqZc7zrNzk94K?usp=sharing
The last failing is 

raceback (most recent call last):
  File "/content/POCO/demo.py", line 313, in <module>
    main(args)
  File "/content/POCO/demo.py", line 167, in main
    detections = tester.run_detector(input_image_folder)
  File "/content/POCO/pocolib/core/tester.py", line 145, in run_detector
    mot = MPT(
  File "/usr/local/lib/python3.10/dist-packages/multi_person_tracker/mpt.py", line 52, in __init__
    self.detector = YOLOv3(
TypeError: YoloV3() got an unexpected keyword argument 'device'

**Comment by Rut-B** [comment]
I trying to run the model without using yolov3
using maskrcnn
seems that your model is not accurate 

see example of image of shapy https://github.com/muelea/shapy/blob/master/samples/images/img_01.jpg
with your code its return :
![000001](https://github.com/saidwivedi/POCO/assets/32880198/f1327b2a-e7a7-4cc3-b36d-107c0ccdec5d)

what I missed?

**Comment by saidwivedi** [comment]
**Installation Failure:** 
I checked the google colab you shared, I think the issue is due installation problem of `YOLOv3`. Can you install as per the instructions mentioned? Try this
`pip install git+https://github.com/mkocabas/yolov3-pytorch.git`

**Shape Estimation**
Like most methods in the HPS community, POCO focuses on pose estimation, largely due to the limited training data with ground-truth shape. Hence, output is mean shape. However, recent synthetic data like [BEDLAM](https://bedlam.is.tue.mpg.de/) tries to address data scarcity. One can potentially use these data to model both pose and shape uncertainty.

Hope it answers your question.

**Comment by Rut-B** [comment]
@saidwivedi thanks of your answer - regard the shape estimation - is it the answer to model accuracy ?
this image 
![image](https://github.com/saidwivedi/POCO/assets/32880198/81effe03-ecd5-450b-8884-6eb0d5855854)
 is the static position and should be simple example of person, seems that body  measurements of is not correct
is it cause that model not training on example of this body?

**Comment by saidwivedi** [comment]
Yes you are right, POCO is not trained on diverse shape as most of the data has mean shape. Hence, the shape is not accurate.
