### ISSUE TITLE
Body measurments

### ISSUE THREAD

**Issue by Rut-B** [saidwivedi/POCO#4]
hi, @saidwivedi 
is it possible to extract the body measurements from the model?
for example height, waist chest and etc?

**Comment by saidwivedi** [comment]
Yes you could use [SHAPY, CVPR 2022](https://github.com/muelea/shapy?tab=readme-ov-file#virtual-measurements) to get body measurements from SMPL 3D mesh. However, POCO is not trained on diverse body shapes so, output body shapes are not very accurate.
